CREATE VIEW VIEW_USER_INFORMATION AS 
SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH,
U.GENDER, CURRENT_C.CITY_NAME, CURRENT_C.STATE_NAME, CURRENT_C.COUNTRY_NAME, HOME_C.CITY_NAME AS HOMETWON_CITY, HOME_C.STATE_NAME AS HOMETOWN_STATE, 
HOME_C.COUNTRY_NAME AS HOMETOWN_COUNTRY, PG.INSTITUTION, EDU.PROGRAM_YEAR, PG.CONCENTRATION, PG.DEGREE
FROM USERS U
LEFT JOIN (USER_CURRENT_CITIES USER_CC
    INNER JOIN CITIES CURRENT_C ON USER_CC.CURRENT_CITY_ID = CURRENT_C.CITY_ID)
ON U.USER_ID = USER_CC.USER_ID
LEFT JOIN (USER_HOMETOWN_CITIES USER_HC
    INNER JOIN CITIES HOME_C ON USER_HC.HOMETOWN_CITY_ID = HOME_C.CITY_ID)
ON U.USER_ID = USER_HC.USER_ID
LEFT JOIN (EDUCATION EDU 
    INNER JOIN PROGRAMS PG ON EDU.PROGRAM_ID = PG.PROGRAM_ID)
ON U.USER_ID = EDU.USER_ID;


CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT * FROM FRIENDS;


CREATE VIEW VIEW_PHOTO_INFORMATION AS 
SELECT  A.ALBUM_ID, A.ALBUM_OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME, A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, 
A.ALBUM_LINK, A.ALBUM_VISIBILITY, P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
FROM ALBUMS A 
LEFT JOIN PHOTOS P  
ON A.ALBUM_ID = P.ALBUM_ID;


CREATE VIEW VIEW_EVENT_INFORMATION AS 
SELECT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE, E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE,
E.EVENT_SUBTYPE, E.EVENT_ADDRESS, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, E.EVENT_START_TIME, E.EVENT_END_TIME
FROM USER_EVENTS E 
LEFT JOIN CITIES C 
ON E.EVENT_CITY_ID = C.CITY_ID;


CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y
FROM TAGS;