DROP TABLE TAGS;
DROP TABLE PHOTOS CASCADE CONSTRAINTS;
DROP TABLE ALBUMS CASCADE CONSTRAINTS;
DROP TABLE PARTICIPANTS;
DROP TABLE USER_EVENTS;
DROP TABLE EDUCATION;
DROP TABLE PROGRAMS;
DROP TABLE MESSAGES;
DROP TABLE USER_HOMETOWN_CITIES; 
DROP TABLE USER_CURRENT_CITIES;
DROP TABLE CITIES;
DROP TABLE FRIENDS;
DROP TABLE USERS CASCADE CONSTRAINTS; 
DROP SEQUENCE CITY_SEQUENCE;
DROP SEQUENCE PROGRAM_SEQUENCE;

